language: generic 
sudo: required
services:
  - docker
before_install:
  - docker build -t aditic/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true aditic/docker-react npm run test -- --coverage
  
